[profile.default]
out = "out"
script = "script"
test = "test"
src = "src"
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 20_000
no_match_coverage = "utils|script|test"
no_match_contract = "TestForkCanaryWstETH"

[profile.fork]
match_contract = "TestForkCanaryWstETH"
no_match_contract = "disabled"



[profile.ci.fuzz]
runs = 10_000
